---
name: 余浔
date: "`r format(Sys.time(), '%B, %Y')`"
address: 安徽省芜湖市
email: nealxun@163.com
phone: +1 979-703-9128
github: nealxun
linkedin: findnealyu
profilepic: profile.png
aboutme: "数据分析从业人员，对人工智能在传统行业的应用保持高度的敏感性和关注度，擅长机器学习，统计建模，能够处理并分析大量繁杂数据，发现其中商业价值并提供决策支持。"
headcolor: "414141"
header-includes:
  - \usepackage{ctex}
output: 
  vitae::awesomecv:
    keep_tex: true
    latex_engine: xelatex
---

```{r setup, include=FALSE}
library(tidyverse)
library(vitae)
knitr::opts_chunk$set(echo = FALSE)
```

# 教育背景

```{r education}
tribble(
  ~ degree, ~ uni, ~ loc, ~ dates,
  "工业工程硕士学位", "美国德州农工大学", "College Station, 得克萨斯州", "2014 - 2016", 
  
  "工业与制造工程学士学位", "美国北达科他州立大学", "Fargo，北达科他州", "2010 - 2013"
) %>% 
  detailed_entries(degree, dates, uni, loc)
```


# 职业履历

```{r working}
tribble(
  ~ role, ~ company, ~ loc, ~ dates, ~ details,
  "预测分析师", "苹果", "加利福利亚州Sunnyvale", "01/2020 - 至今", 
    list("负责整个欧洲市场的顾客需求分析工作，对超过24种语言和100多条专线提供及时准确的预测。",
         "拓展单因子时间序列模型至多因子以应对新冠疫情对客户需求带来的影响，并提出预测之前先分类的概念，提升5\\%的预测准确率。",
         "通过将客服人员工作年限，工作级别等因素纳入预测模型，以及应用智能模型选择算法，显著提升了高阶客户需求的预测准确性大约4\\%。"
        ),
  
  "统计分析师", "特斯拉", "加利福利亚州Fremont", "09/2017 - 12/2019", 
    list("从零开始创建多个统计预测模型（ETS, ARIMA, Dynamic Regression等），对全球超过12,000 个汽车零部件的需求进行Global以及PDC层面的预测，准确率达80%。", 
         "使用SQL获取各PDC各个零部件的库存状况，并根据每月的库存转移数据，提出有效季度库存清算建议。",
        "建立基于R Shiny的数据可视化面板，有效监控各个模型的预测准确率并给需求规划专员提供实时反馈。",
         "基于汽车零部件平均替换周期及尺寸大小，预测3-5年内全球范围内的整体消耗量以帮助仓库规划产能。",
         "创建整数规划模型，将零部件划分给不同需求规划专员以平衡工作量并分散风险。"
         ),
  
  "商业智能分析员", "美国Spotlight能源公司", "得克萨斯州休斯敦", "08/2016 – 09/2017", 
    list("设计Python网络爬虫，从管道运输公司EBB中自动抓取有关天然气运输的关键信息，每年节约人力成本\\$15K。", 
         "创建Excel数据模型，自动导入交易数据并计算公司每日的损益值，提升50\\%的效率。",
         "创建交易最优化模型，根据每日天然气价格的浮动以及对手方的交易策略，自动计算出各条运输路径的利润。"
         ),
  
    "仓储精益专员", "京东", "上海", "05/2016 – 08/2016", 
    list("负责仓库各项运营环节的监控与改善工作，提出的飞鹰计划帮助公司节省10万余元。", 
         "参与对顾客在网上评论数据的分析与挖掘，进而改善仓储作业流程提升部分商品的客户满意度2\\%。"
         )
        ) %>% 
  detailed_entries(role, dates, company, loc, details)
```

\newpage
# 项目经历

```{r project}
tribble(
  ~ title, ~ dates, ~ details,
  "美国德州农工大学，教育学院，智能教师模型设计", "03/2016 – 05/2016", 
    list("利用隐含马尔科夫模型预测小学低年级学生在客观题上答对每一题的概率，为智能教师的创立提供理论基础。",
         "创建神经网络模型，根据学生答题产生的序列预测该陷入“高原区”的可能性，提高recall 50\\%，precision 10\\%。"
         ),
  
    "美国德州农工大学，工业与系统工程学院，半导体行业次品预测模型设计", "05/2015 – 08/2015", 
    list("利用主成分分析法将原始数据的维度从590降至168，有效减少数据的噪音程度。",
         "针对原始数据的不平衡情况，运用多次取样的方法将模型的预测精度提升了10\\%。"
         )
        ) %>% 
  detailed_entries(what = title, when = dates, why = details)
```


# 职业证书

```{r awards, results='asis'}
# oneline
tribble(
    ~ category,
    "工程：美国基础工程师从业资格证书，美国工业工程协会六西格玛绿带证书",
    "计算机：能够熟练使用 SQL, R, Python, Tableau, Excel Power Query, Excel Power Pivot",
    "其他：通过CFA一级考试，SAS 全球基础资格认证书，美国德州农工大学梅斯商学院商业管理证书"
  ) %>%
        detailed_entries(why = category)

```
